# We will use docker to set up our environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

env:
    global:
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
    matrix:
        - DIST=xenial

install: beaver install

script:
    - beaver make USE_BLAS=openblas USE_OPENCV=0 USE_OPENMP=0
    - beaver make -f pkg/Makefile F=production pkg

deploy:
    provider: script
    script: beaver bintray upload -d sociomantic-tsunami/mxnet/libmxnet build/last/pkg/*.deb
    skip_cleanup: true
    on:
        tags: true
